name: "Coap2MQTT"
description: "CoAP server that forwards messages to the Home Assistant MQTT broker"
version: "1.0.0"
slug: "coap_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  secret: "secret string"
schema:
  secret: str
ports:
  5683/udp: 5683